ai: ""
android: ""
apple: ""
audio: ""
avro: ""
c: ""
clj: ""
coffee: ""
conf: ""
cpp: ""
css: ""
d: ""
dart: ""
db: ""
diff: ""
doc: ""
docker: ""
ebook: ""
env: ""
epub: ""
erl: ""
file: ""
font: ""
gform: ""
git: ""
go: ""
gruntfile.js: ""
hs: ""
html: ""
image: ""
iml: ""
java: ""
class: ""
js: ""
json: ""
jsx: ""
less: ""
log: ""
lua: ""
swift: ""
md: ""
mustache: ""
npmignore: ""
pdf: ""
php: ""
pl: ""
ppt: ""
psd: ""
py: ""
r: ""
rb: ""
rdb: ""
rss: ""
rubydoc: ""
sass: ""
scala: ""
shell: ""
sqlite3: ""
styl: ""
tex: ""
ts: ""
twig: ""
txt: ""
video: ""
vim: ""
windows: ""
xls: ""
xml: ""
yarn.lock: ""
yml: ""
toml: ""
zip: ""
save: ""
pysave: ""
bak: "󰁯"
itermcolors: "󰌁"
zwc: ""
